### PR TITLE
fix color-coding to work with older bash-versions

### PR DESCRIPTION
**Pull request by pjwalstrom**
ref https://github.com/nais/device/issues/138

### CODE REVIEW

**Review by x10an14 — COMMENTED** [review]
LGTM - just need to confirm that the same color-codes work in Zsh on a Mac =) Will get a chance to test tomorrow.

**Comment by pjwalstrom** [comment]
Ended up just changing escape-character. Tested and works on 
- bash 3.2.57 (os x) 
- bash 4.4.23 (git bash on windows) 
- zsh 5.7.1 (os x)

**Review by x10an14 — CHANGES_REQUESTED** [review]
Screenshot from 2020-10-14 11-28-10
Screenshot from 2020-10-14 11-27-59

As above two screenshots show, there's now a bug introduced with the blinking =/

I'm running Bash on Gnome-Terminal (Linux).

**Comment by x10an14** [comment]
Nvm, when testing the old `ok` line utilizing `\e` instead of `\033` it still blinks. So this PR introduced no new bug as such. Approved!

**Review by x10an14 — APPROVED** [review]

**Pull request merged**
