### PR TITLE
Make install script support linux

### PR DESCRIPTION
**Pull request by mortenlj**
With these changes, the script should be able to work on both linux and macos. The script has been tested on my xubuntu, but probably a good idea to test on mac and other linux'es.

### CODE REVIEW

**Comment by mortenlj** [comment]
Turns out apt-get does support absolute path to a deb-file, even if the man-page said it doesn't. Also fixed an incorrect usage of `mktemp`.

**Review by x10an14 — APPROVED** [review]
LGTM!
-- nvm, unable to get it to work locally.

Investigating...

**Review by x10an14 — APPROVED** [review]
Now it works for me locally! The install at least =)
LGTM!

**Comment by mortenlj** [comment]
@x10an14 : grep (and mktemp) on Mac are BSD versions, which are limited in which options it supports. Changed back to what works on both platforms.

**Pull request merged**
